### PR TITLE
Tweets save in database

### PR DESCRIPTION
**Pull request by izMystic**
post issues you have in here so I can fix them asap

### CODE REVIEW

**Comment by WooAf** [comment]
`SELECT * FROM phone_tweets WHERE citizenid = ?`

Should be
`
SELECT * FROM phone_tweets`


Otherwise you will load only YOUR tweet and not the whole tweeter

**Comment by izMystic** [comment]
Yep, you're right

**Comment by AyPiXt** [comment]
image
getting this error when i try to add this to the tables any clue ??

**Review by ansljeremy — APPROVED** [review]
Tested and working so far on my server

**Comment by Manliketjb** [comment]
Tried this out, keep getting this when sending message
Screenshot 2021-12-13 153520
s

**Comment by CptNoHand** [comment]
Tested it for few days and it works for us

**Comment by Manliketjb** [comment]
Redownloaded the phone, made the edits.. still can't get it to work

**Comment by izMystic** [comment]
make sure youre running the right SQL
```sql
CREATE TABLE IF NOT EXISTS `phone_tweets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50) DEFAULT NULL,
  `firstName` varchar(25) DEFAULT NULL,
  `lastName` varchar(25) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `date` datetime DEFAULT current_timestamp(),
  `url` text DEFAULT NULL,
  `picture` text DEFAULT './img/default.png',
  `tweetId` varchar(25) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`)
) ENGINE=InnoDB AUTO_INCREMENT=1;
```

**Comment by izMystic** [comment]
> image getting this error when i try to add this to the tables any clue ??

probably due to the SQL client youre using, try running it on [phpMyAdmin](http://localhost/phpmyadmin)

**Comment by jaxonfromkh** [comment]
can't delete post that has pic

**Comment by xenfovn** [comment]
cant get tweet id

**Comment by Manliketjb** [comment]
Still getting an Unknown Column.. deleted and downloaded 4 times, on a old recipe and a completely new recipe and still the same error

**Comment by jaxonfromkh** [comment]
> Still getting an Unknown Column.. deleted and downloaded 4 times, on a old recipe and a completely new recipe and still the same error

Just Change id in local Data TID

**Comment by Manliketjb** [comment]
> > Still getting an Unknown Column.. deleted and downloaded 4 times, on a old recipe and a completely new recipe and still the same error
> 
> Just Change id in local Data TID

I'm still leaning about SQL stuff so i dunno what you mean lol

**Comment by izMystic** [comment]
> can't delete post that has pic

you cant delete any post

**Comment by izMystic** [comment]
> cant get tweet id

can i have more details? just "cant get tweet id" doesnt help me

**Comment by izMystic** [comment]
> Still getting an Unknown Column.. deleted and downloaded 4 times, on a old recipe and a completely new recipe and still the same error

check your database tables, remove phone_tweets if you have it, then run this sql
```sql
CREATE TABLE IF NOT EXISTS `phone_tweets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50) DEFAULT NULL,
  `firstName` varchar(25) DEFAULT NULL,
  `lastName` varchar(25) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `date` datetime DEFAULT current_timestamp(),
  `url` text DEFAULT NULL,
  `picture` text DEFAULT './img/default.png',
  `tweetId` varchar(25) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`)
) ENGINE=InnoDB AUTO_INCREMENT=1;
```

**Comment by xenfovn** [comment]
cant delete tweet post , pls fix it

**Comment by Manliketjb** [comment]
Screenshot 2021-12-18 200141
redownloaded on and made the edits, now i'm getting this error

**Comment by antsleem** [comment]
This issue is still occurring, latest MariaDB version, fresh install straight from TXAdmin.

**Comment by antsleem** [comment]
[ERROR] qb-phone was unable to execute a query!
[      script:oxmysql]         Incorrect datetime value: '2021-12-28T03:47:39.772Z' for column `qbcoreframework_c1b387`.`phone_tweets`.`date` at row 1
[      script:oxmysql]         INSERT INTO phone_tweets (citizenid, firstName, lastName, message, date, url, picture, tweetid) VALUES ('DBB42220', 'Anton', 'Developer', 'd', '2021-12-28T03:47:39.772Z', '', 'default', 'TWEET-51173279')

Reinserted the DB table as pasted above by mystic, still erroring.

**Pull request merged**
