### PR TITLE
Adding Emergency Service control center

### PR DESCRIPTION
**Pull request by CodeRedDev**
This addition gives players of `police` or `ambulance` job the ability to enter the control center.

The control center serves the purpose that civilians can call `911` or `912` for emergency services and will be forwarded to the person who is currently operating the control center.

Control center operators will see the caller's phone number but callers won't see the operators personal phone number. Instead they will see the Emergency Service number in their recent calls.

PS: @ItsANoBrainer please leave me one of those crispy gif reviews here 🤩

### CODE REVIEW

**Review by merpindia — APPROVED** [review]
nice idea

**Comment by CodeRedDev** [comment]
Some additional info: On player logout the control center should be cleared. Unfortunately this does not happen if the player quits by F8 or similar methods. Thus with `/clearcontrolcenter [job]` the admin or a boss of the given job can clear the control center.

**Comment by divide29** [comment]
@CodeRedDev 

Hey, sind die Leitstellen hier getrennt, d.h. Rettungsdienst hat eine und die Polizei eine je nach Nummer?

English: Are the jobs seperated to have own control centers?

**Comment by CodeRedDev** [comment]
Yes the jobs are separated. 911 is mapped to police and 912 is mapped to ambulance.

With some scripting you can also add other jobs too.

**Review by sinphoenix — APPROVED** [review]

**Pull request closed without merging**
