### PR TITLE
complete trucker job application

### PR DESCRIPTION
**Pull request by darknight2590**
We will complete the application with you trucker
The source is the original version of the project , Some of the code is present in the project by default, but it is incomplete

### CODE REVIEW

**Comment by darknight2590** [comment]
and Script qb-truckerjob is being updated

**Comment by darknight2590** [comment]
https://github.com/qbcore-framework/qb-truckerjob/pull/6

**Comment by darknight2590** [comment]
https://pasteboard.co/KhZAWfy.png

**Comment by darknight2590** [comment]
@GhzGarage 
Source from the old official project

**Comment by am3nd01m** [comment]
I have the following issue:
imagem

**Comment by darknight2590** [comment]
https://github.com/qbcore-framework/qb-truckerjob/pull/6
@am3nd01m

**Review by Eralpozcan — CHANGES_REQUESTED** [review]
- UI, CSS,HTML , Okay. work for me.


- JS Request changes and check.
- Exports check.

**Comment by darknight2590** [comment]
I hope to see this addition soon on the phone, one of the job in sync with the phone, multi-functionality and ideas are good for the project

**Comment by Eralpozcan** [comment]
In fact, he had minor problems, so I requested a change. It was very useful when I reviewed the code, but I didn't have enough time to solve the problems.
Actually, if there is no conflict in the sense of the idea, can you update it and reopen it?

**Pull request closed without merging**
