### PR TITLE
TEMPLATE CHANGED

### PR DESCRIPTION
**Pull request by yamieboi**
IPHONE TEMPLATE WITH GLARE

CSS EDITED

### CODE REVIEW

**Comment by uShifty** [comment]
This commit reverts the previous commit adding the ability to delete tweets ect. Also you left in your webhook url in the server side

**Comment by yamieboi** [comment]
> This commit reverts the previous commit adding the ability to delete tweets ect. Also you left in your webhook url in the server side

this phone is like maybe 9-10 hours old that could be why and the webhook i have removed it from my discord server.

**Comment by yamieboi** [comment]
image


EXAMPLE

**Comment by yamieboi** [comment]
UPDATE: fixed a little issue with the width and updated the phone to the latest release.

**Comment by yamieboi** [comment]
image

image

looks like this now

**Comment by Eralpozcan** [comment]
If you tell me how it looks on all applications with a video. It would be more descriptive for Kakarot or Maintenance Team.

**Comment by yamieboi** [comment]
> If you tell me how it looks on all applications with a video. It would be more descriptive for Kakarot or Maintenance Team.

it looks pretty good if you want you can download the fork and test it out. i cant really make a video at the moment i am a bit busy.

**Pull request closed without merging**
