### PR TITLE
Linux

### PR DESCRIPTION
**Pull request by jay-fivem**

### CODE REVIEW

**Comment by amantu-qbit** [comment]
?????????????????????

**Comment by Mojito-Fivem** [comment]
Linux?

**Comment by jay-fivem** [comment]
Just fix for some Linux versions

**Comment by Mojito-Fivem** [comment]
It's exactly the same

**Comment by BerkieBb** [comment]
No, it's just the time stamp that got removed for linux

**Comment by Mojito-Fivem** [comment]
ok

**Comment by zfbx** [comment]
So I know this was merged.. but why isn't this just a ternary on the value itself? o.O and why does this break on linux anyways?

**Pull request merged**
