### PR TITLE
fix(garages): Blank phone screen | v1 garages

### PR DESCRIPTION
**Pull request by Sharkiiie**
## Description

Fixes blank phone screen and removed old v1 garage data handling.

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by SirDoodlesNY** [comment]
I did a fresh install on QB-Core onto my server and the phone was blank except for the qbcore image. I tried the updated qb-phone as of today and I am still getting the blank screen on the phone. After the update I did a full restart of the server too.

blank_phone

**Comment by Sharkiiie** [comment]
@SirDoodlesNY Did you add the changes from this PR?
This PR has not been merged yet. There is another in qb-garages to fix another bug with the vehicles app.

**Comment by SirDoodlesNY** [comment]
> @SirDoodlesNY Did you add the changes from this PR? This PR has not been merged yet. There is another in qb-garages to fix another bug with the vehicles app.

@Sharkiiie It is working now. 

This is my first time using GitHub for working with issues, I didn't know to do the other PR's to fix it. Thanks :)

**Review by singh-manavv — APPROVED** [review]
This PR fixed the changes caused in the previous PR.

**Pull request merged**
