### PR TITLE
Improve Invoice/ Undefined coords error/handcuffed error solve

### PR DESCRIPTION
**Pull request by Eralpozcan**
- Add taxi job for invoice
- Add Comment(Explain Bill) in Bill Command.
- Add sender society name `text-transform:Capitalize` 

**Update: 17/10**
- Add lawyer job for bill commands.
- Add Undefined coords error solve in Meos.

I added the explanation part of the invoice when issuing an invoice. In this way, people will be able to see what he paid for or with a description of it in some way. After all, we know or want to know why the bill is.

I also made it mandatory to enter a description.

https://prnt.sc/1wfn1xy

### CODE REVIEW

**Comment by evanillaa** [comment]
Can you add these jobs to config.lua ?
if biller.PlayerData.job.name == "police" or biller.PlayerData.job.name == 'ambulance' or biller.PlayerData.job.name ==
        'mechanic' or biller.PlayerData.job.name == "taxi" then

**Review by evanillaa — APPROVED** [review]

**Review by tony-stark-17 — APPROVED** [review]
-LGTM

**Comment by Eralpozcan** [comment]
I changed the Fetch change without having to open PR again.

**Comment by Eralpozcan** [comment]
I'm closing because the billing system will change. Other arrangements will be in a new PR.

**Pull request closed without merging**
